<?php

/**
 * @file
 * Defines all the hooks this module implements.
 */

/**
 * Implements hook_menu().
 */
function islandora_panorama_krpano_menu() {
  return array(
    'admin/islandora/islandora_viewers/panorama_krpano' => array(
      'title' => 'KRPano Panorama Viewer',
      'description' => 'Configure the KRPano Panorama Viewer.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_panorama_krpano_admin_settings_form'),
      'access arguments' => array('administer site configuration'),
      'file' => 'includes/admin.form.inc',
      'type' => MENU_NORMAL_ITEM,
    ),
    'panorama_krpano_dimensions/%islandora_object' => array(
      'page callback' => 'islandora_panorama_krpano_dimensions_callback',
      'page arguments' => array(1),
      'access callback' => 'islandora_object_access_callback',
      'access arguments' => array(ISLANDORA_VIEW_OBJECTS, 1),
      'file' => 'includes/callback.inc',
      'type' => MENU_CALLBACK,
    ),
    'panorama_krpano_text/%islandora_object' => array(
      'page callback' => 'islandora_panorama_krpano_text_callback',
      'page arguments' => array(1),
      'access callback' => 'islandora_object_access_callback',
      'access arguments' => array(ISLANDORA_VIEW_OBJECTS, 1),
      'file' => 'includes/callback.inc',
      'type' => MENU_CALLBACK,
    ),
    'panorama_krpano_search/%' => array(
      'page callback' => 'islandora_panorama_krpano_search_callback',
      'page arguments' => array(1, 2),
      'access callback' => 'user_access',
      'access arguments' => array(ISLANDORA_VIEW_OBJECTS),
      'file' => 'includes/callback.inc',
      'type' => MENU_CALLBACK,
    ),
    'panorama_krpano_xml/%islandora_object' => array(
	'page callback' => 'islandora_panorama_krpano_xml_callback',
	'page arguments' => array(1),
	'access callback' => 'user_access',
	'access arguments' => array(ISLANDORA_VIEW_OBJECTS),
	'file' => 'includes/callback.inc',
	'type' => MENU_CALLBACK,
    ),
   'panorama_krpano_embed/%islandora_object' => array(
        'page callback' => 'islandora_panorama_krpano_embed_callback',
        'page arguments' => array(1),
        'access callback' => 'user_access',
        'access arguments' => array(ISLANDORA_VIEW_OBJECTS),
        'file' => 'includes/callback.inc',
        'type' => MENU_CALLBACK,
    ),
  );
}

/**
 * Implements hook_theme().
 */
function islandora_panorama_krpano_theme() {
  return array(
    'islandora_panorama_krpano' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/islandora-panorama-krpano',
      'variables' => array(
        'object' => NULL,
        'datastream_id' => 'JP2',
        'page_progression' => 'rl',
        'pages' => array(),
      ),
    ),
    'islandora_panorama_krpano_panorama_info' => array(
      'file' => 'theme/theme.inc',
      'variables' => array(
	'object' => NULL,
	),
    ),
  );
}

/**
 * Implements hook_islandora_viewer_info().
 */
function islandora_panorama_krpano_islandora_viewer_info() {
  return array(
    'islandora_panorama_krpano' => array(
      'label' => t('KRPano Panorama Viewer'),
      'description' => t('KRPano Panorama Viewer.'),
      'configuration' => 'admin/islandora/islandora_viewers/panorama_krpano',
      'callback' => 'islandora_panorama_krpano_viewer_callback',
      'model' => array(
        'islandora:panoramaCModel',
      ),
    ),
  );
}

/**
 * Callback function for the viewer.
 *
 * @param array $params
 *   The params for the theme function 'islandora_panorama_krpano'.
 *
 * @return string
 *   HTML representation of the KRPano Panorama Viewer.
 */
function islandora_panorama_krpano_viewer_callback(array $params) {
  return theme('islandora_panorama_krpano', $params);
}
