<?php

/**
 * @file
 * Defines the install/uninstall hooks for this module.
 */

/**
 * Implements hook_uninstall().
 */
function islandora_panorama_krpano_uninstall() {
  $variables = array(
    'islandora_panorama_krpano_djatoka_url',
    'islandora_panorama_krpano_compression',
    'islandora_panorama_krpano_ocr_field',
    'islandora_panorama_krpano_ocr_filter_field',
    'islandora_panorama_krpano_solr_result_count',
    'islandora_panorama_krpano_sequence_number',
    'islandora_panorama_krpano_overlay_opacity',
    'islandora_panorama_krpano_default_page_view',
  );
  // Delete the Drupal variables defined by this module.
  array_walk($variables, 'variable_del');
}
